### ISSUE TITLE
Error: Command failed: hostnamectl

### ISSUE THREAD

**Issue by erickgonzalezs** [madereddy/EarnApp-Docker#17]
![image](https://github.com/madereddy/EarnApp-Docker/assets/46759695/a9819418-e20a-41e5-87a1-443239c0b0f8)

**Comment by madereddy** [comment]
@erickgonzalezs Can you try the latest docker image build? Pushed a newer commit: https://github.com/madereddy/EarnApp-Docker/commit/f5321d982679417e6899ee155e8c08d57f0b33c7 which should fix it.

**Comment by erickgonzalezs** [comment]
Excelent!!! 

![image](https://github.com/madereddy/EarnApp-Docker/assets/46759695/21b967d3-c083-475c-874c-829d98e8ce0b)


Thanks!!!

**Comment by madereddy** [comment]
Sweet, glad it worked. Closing this issue.
