### ISSUE TITLE
Docker containers stopped working

### ISSUE THREAD

**Issue by vstrong-info** [madereddy/EarnApp-Docker#26]
Docker container stopped working:

`Installing
earnapp[10]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x991f18 node::Abort() [earnapp]
 2: 0x991f88  [earnapp]
 3: 0x9f9070 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [earnapp]
 4: 0x9f915c node::NodePlatform::NodePlatform(int, v8::TracingController*) [earnapp]
 5: 0x961a8c node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [earnapp]
 6: 0x961fc4 node::Start(int, char**) [earnapp]
 7: 0x7f941884c4  [/lib/aarch64-linux-gnu/libc.so.6]
 8: 0x7f94188598 __libc_start_main [/lib/aarch64-linux-gnu/libc.so.6]
 9: 0x8ea230  [earnapp]
/usr/bin/install: line 9:    10 Aborted                 (core dumped) earnapp stop
earnapp[12]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x991f18 node::Abort() [earnapp]
 2: 0x991f88  [earnapp]
 3: 0x9f9070 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [earnapp]
 4: 0x9f915c node::NodePlatform::NodePlatform(int, v8::TracingController*) [earnapp]
 5: 0x961a8c node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [earnapp]
 6: 0x961fc4 node::Start(int, char**) [earnapp]
 7: 0x7f967a84c4  [/lib/aarch64-linux-gnu/libc.so.6]
 8: 0x7f967a8598 __libc_start_main [/lib/aarch64-linux-gnu/libc.so.6]
 9: 0x8ea230  [earnapp]
/usr/bin/install: line 11:    12 Aborted                 (core dumped) earnapp start
Earnapp is running
earnapp[14]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x991f18 node::Abort() [earnapp]
 2: 0x991f88  [earnapp]
 3: 0x9f9070 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [earnapp]
 4: 0x9f915c node::NodePlatform::NodePlatform(int, v8::TracingController*) [earnapp]
 5: 0x961a8c node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [earnapp]
 6: 0x961fc4 node::Start(int, char**) [earnapp]
 7: 0x7fb33184c4  [/lib/aarch64-linux-gnu/libc.so.6]
 8: 0x7fb3318598 __libc_start_main [/lib/aarch64-linux-gnu/libc.so.6]
 9: 0x8ea230  [earnapp]
/usr/bin/install: line 14:    14 Aborted                 (core dumped) earnapp run
`

`uname -a

Linux raspberrypi 5.10.52-v8+ #1441 SMP PREEMPT Tue Aug 3 18:14:03 BST 2021 aarch64 GNU/Linux`

**Comment by vstrong-info** [comment]
It works on some but not all Linux builds - hence I provided the name -a output:
```
uname -a
Linux raspberrypi 5.10.52-v8+ #1441 SMP PREEMPT Tue Aug 3 18:14:03 BST 2021 aarch64 GNU/Linux
```

**Comment by madereddy** [comment]
Were you able to test the older container version? Did that have the same issue? I tested on two different pi's (3b and 4) and two different linux hosts without any issues.

**Comment by vstrong-info** [comment]
What branch should I select? `madereddy/earnapp:???`

**Comment by madereddy** [comment]
You can use this command ```docker pull madereddy/earnapp:1.466.560```. All old containers are versioned as well: https://hub.docker.com/r/madereddy/earnapp/tags

**Comment by madereddy** [comment]
Did you try the pinned version? Did that help?
